import { access, mkdir, readFile, writeFile } from "fs";
import { Listr } from "listr2";
import { resolve } from "path";
import { promisify } from "util";

const writeFilePromise = promisify(writeFile);
const readFilePromise = promisify(readFile);
const mkdirPromise = promisify(mkdir);

const nameServerPath = "/etc/resolver/";
const resolverPath = resolve(nameServerPath, 'docker');
const dnsMasqContents = `# Generated by 4M's dnsmasq
nameserver 127.0.0.1
port 19322
`;

const fileExists = (path) =>
  new Promise((resolve) => access(path, undefined, (err) => resolve(!err)));

export const darwinDnsMasq = async () => {
  await new Listr([
    {
      title: "Setting up DNS Masq for Darwin platform",
      task: (ctx, task) => {
        return task.newListr(
          [
            {
              title: "Validate sudo access is given",
              task: async (ctx, task) => {
                if (await fileExists(nameServerPath)) ctx.skip = true;
              },
            },
            {
              title: "Creating name server configuration directory",
              skip: (ctx): boolean => ctx.skip,
              task: async () => {
                try {
                  await mkdirPromise(nameServerPath);
                } catch (err: any) {
                  if (err.code === "EACCES")
                    throw new Error(
                      "This task needs elevated permissions. Please run again using sudo. This only needs to be done once."
                    );
                  throw err;
                }
              },
            },
            {
                title: 'Creating dns configuration file',
                task: async () => {
                  try {
                    await writeFilePromise(resolverPath, dnsMasqContents);
                  } catch (err: any) {
                    task.output = err;
                    if (err.code === 'EACCES')
                      throw new Error(
                        'This task needs elevated permissions. Please run again using sudo. This only needs to be done once.',
                      );
                  }
                },
              },
          ],
          {
            concurrent: false,
            rendererOptions: { showSubtasks: true, collapse: false },
          }
        );
      },
    },
  ]).run();
};
